# vim: set fileencoding=utf-8:

charmap = {'1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '0': 0, '一': 1, '壹': 1, '二': 2, '贰': 2, '三': 3, '叁': 3, '四': 4, '肆': 4, '五': 5, '伍': 5, '六': 6, '陆': 6, '七': 7, '柒': 7, '八': 8, '捌': 8, '九': 9, '玖': 9, '零': 0, '+': '+', '加': '+', '=': '=', '?': '?'}

template = {
'1': [[False, False, False, True, True],
      [False, False, True, True, True],
      [True, True, True, True, True],
      [True, True, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True],
      [False, False, True, True, True]],

'2': [[False, False, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, False, False, False, False, True, True, True],
      [False, False, False, False, True, True, True, False],
      [False, False, False, False, True, True, True, False],
      [False, False, False, True, True, True, False, False],
      [False, False, True, True, True, False, False, False],
      [False, False, True, True, True, False, False, False],
      [False, True, True, True, False, False, False, False],
      [True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True]],

'3': [[False, False, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, False, False, False, False, True, True, True],
      [False, False, False, True, True, True, True, False],
      [False, False, False, True, True, True, True, False],
      [False, False, False, False, False, True, True, True],
      [False, False, False, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, True, False, False]],

'4': [[False, False, False, False, False, True, True, True, False, False],
      [False, False, False, False, True, True, True, True, False, False],
      [False, False, False, False, True, True, True, True, False, False],
      [False, False, False, True, True, True, True, True, False, False],
      [False, False, True, True, False, True, True, True, False, False],
      [False, False, True, True, False, True, True, True, False, False],
      [False, True, True, False, False, True, True, True, False, False],
      [True, True, False, False, False, True, True, True, False, False],
      [True, True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True, True],
      [False, False, False, False, False, True, True, True, False, False],
      [False, False, False, False, False, True, True, True, False, False],
      [False, False, False, False, False, True, True, True, False, False]],

'5': [[False, False, True, True, True, True, True, False],
      [False, False, True, True, True, True, True, False],
      [False, True, True, True, False, False, False, False],
      [False, True, True, False, False, False, False, False],
      [False, True, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, False],
      [True, True, True, False, False, True, True, True],
      [False, False, False, False, False, True, True, True],
      [False, False, False, False, False, True, True, True],
      [False, False, False, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, True, False, False]],

'6': [[False, False, False, True, True, True, False, False],
      [False, True, True, True, True, True, True, True],
      [False, True, True, False, False, True, True, True],
      [True, True, True, False, False, False, False, False],
      [True, True, True, True, True, True, False, False],
      [True, True, True, True, True, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, False, False, True, True, True],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, True, False, False]],

'7': [[True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True],
      [False, False, False, False, False, True, True, True],
      [False, False, False, False, True, True, True, False],
      [False, False, False, False, True, True, False, False],
      [False, False, False, True, True, True, False, False],
      [False, False, False, True, True, False, False, False],
      [False, False, True, True, True, False, False, False],
      [False, False, True, True, True, False, False, False],
      [False, False, True, True, False, False, False, False],
      [False, True, True, True, False, False, False, False],
      [False, True, True, True, False, False, False, False],
      [False, True, True, True, False, False, False, False]],

'8': [[False, False, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, True, False, False],
      [False, True, True, False, False, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, True, False, False]],

'9': [[False, False, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, False],
      [True, True, True, False, False, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, True, True, True, True, True],
      [False, False, True, True, True, True, True, True],
      [False, False, False, False, False, True, True, True],
      [True, True, True, False, False, True, True, False],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, False, False, False]],

'0': [[False, False, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, False],
      [False, True, True, False, False, True, True, False],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [True, True, True, False, False, True, True, True],
      [False, True, True, False, False, True, True, False],
      [False, True, True, True, True, True, True, False],
      [False, False, True, True, True, True, False, False]],

#'一': [[False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False],
#       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]],

'壹': [[False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, True, True, False, False, False, True, True, True, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, True, True, False, False, True, True, True, False, False],
       [False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [False, True, True, False, False, False, False, False, False, False, False, True, True, True, False, True, False],
       [True, True, True, False, True, True, True, True, True, True, True, True, True, True, False, False, False],
       [False, False, True, True, False, False, False, False, False, False, False, False, True, True, False, False, False],
       [False, False, False, True, True, True, True, True, True, True, True, True, True, True, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, False, True, True, False, False, False],
       [False, False, False, True, True, True, True, True, True, True, True, True, True, True, False, False, False],
       [False, False, False, True, True, True, False, False, False, False, True, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, True, True, False, False, True, True, True],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]],

#'二': [[False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, False, False],
#       [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
#       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False],
#       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]],

'贰': [[False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, True, True, False, True, True, True, False],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [False, False, False, False, False, False, True, True, False, False, True, True, False, False, False, False, False],
       [False, True, True, True, True, True, True, True, True, False, False, True, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, True, True, False, True, False, False, False, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False],
       [True, True, False, False, False, False, False, True, True, False, False, True, False, False, False, False, False],
       [False, True, True, True, True, True, True, True, True, True, False, True, True, False, False, False, False],
       [False, True, True, False, True, True, True, True, True, False, False, True, True, False, False, False, False],
       [False, True, True, False, True, True, False, True, True, False, False, True, True, False, False, False, False],
       [False, True, True, False, True, True, False, True, True, False, False, True, True, False, False, False, False],
       [False, True, True, False, True, True, False, True, True, False, False, False, True, True, False, False, False],
       [False, True, True, False, True, True, False, True, True, False, False, False, True, True, False, False, False],
       [False, False, False, False, True, False, True, True, False, False, False, False, False, True, True, True, False],
       [False, False, True, True, False, False, False, True, True, False, False, False, False, True, True, True, False],
       [False, True, True, False, False, False, False, False, False, False, False, False, False, False, True, True, True]],

'三': [[False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, True, True, True, False, False, False],
       [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]],

'叁': [[False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, True, True, True, True, True, True, False, False, False],
       [False, False, False, True, True, True, True, True, True, False, False, False, True, True, False, False, False],
       [False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, True, True, True],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, True, True, True, False, False, False, False],
       [False, False, False, True, True, True, True, True, True, True, True, True, True, True, False, False, False],
       [False, False, True, True, False, False, False, False, False, False, False, False, False, True, True, True, False],
       [True, True, True, False, False, False, False, False, False, False, True, True, False, False, True, True, False],
       [False, False, False, False, True, True, True, True, True, True, True, True, True, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]],

'四': [[True, True, False, False, False, False, False, False, False, False, False, False, False, True, True],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, False, True, True, False, False, True, True, False, False, False, True, True],
       [True, True, False, True, True, False, False, False, True, True, False, False, False, False, True],
       [True, True, False, True, True, False, False, False, True, True, True, True, True, False, True],
       [True, True, False, True, False, False, False, False, False, False, False, False, False, False, True],
       [True, True, False, False, False, False, False, False, False, False, False, False, False, True, True],
       [True, True, False, False, False, False, False, False, False, False, False, False, False, True, True],
       [True, True, False, False, False, False, False, False, False, False, False, False, False, True, True],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [True, True, False, False, False, False, False, False, False, False, False, False, False, True, True]],

'肆': [[False, False, False, False, False, True, True, False, False, False, True, True, True, False, False, False, False],
       [False, True, True, True, True, True, True, True, False, False, True, True, False, False, True, False, False],
       [False, True, True, False, False, False, False, False, True, True, True, True, True, True, True, False, False],
       [False, True, True, False, False, True, True, False, False, False, True, True, False, True, True, False, False],
       [False, True, True, True, True, True, True, False, False, False, True, True, False, True, True, True, True],
       [False, True, True, False, False, True, True, True, True, True, True, True, True, True, True, False, False],
       [False, True, True, True, True, True, True, False, False, False, True, True, False, True, True, False, False],
       [False, True, True, False, False, False, False, False, False, True, True, True, True, True, True, True, False],
       [False, True, True, False, False, False, True, True, False, False, True, True, False, False, False, False, False],
       [True, True, True, True, True, True, True, True, False, False, True, True, False, True, True, False, False],
       [False, False, True, True, False, False, False, True, True, True, True, True, True, True, True, True, False],
       [False, False, True, True, False, True, False, False, False, False, True, True, False, False, True, True, False],
       [False, True, True, False, False, True, True, False, True, True, True, True, True, True, True, True, True],
       [True, True, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [True, True, False, True, True, True, True, True, False, False, True, True, False, False, False, False, False],
       [True, True, True, False, False, False, True, True, False, False, True, True, False, False, False, False, False]],

'五': [[False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False],
       [False, False, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, True, True, False, True, True, False],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]],

'伍': [[False, False, False, True, True, True, False, False, False, False, False, False, False, False, True, True, False],
       [False, False, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True],
       [False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, True, True, False, False, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, True, True, False, False, False, False, False, True, True, False, False, False, False, False, False],
       [False, True, True, True, False, False, False, False, True, True, False, False, False, False, False, False, False],
       [False, True, True, True, False, False, False, False, True, True, False, False, False, True, True, False, False],
       [True, True, True, True, False, False, True, True, True, True, True, True, True, True, True, False, False],
       [False, False, True, True, False, False, False, False, True, True, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, False, True, True, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, False, True, True, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, False, True, True, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, True, True, True, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, True, True, False, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, True, True, False, False, False, False, True, True, False, True],
       [False, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True]],

'六': [[False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, True, True, False, False, False, False, True, True, False],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, False, False, True, True, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, False, False, True, True, False, False],
       [False, False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, False],
       [False, True, True, False, False, False, False, False, False, False, False, False, False, False, True, True, False],
       [True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True]],

'陆': [[False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [True, True, True, True, True, True, True, False, False, False, True, True, False, False, False, False, False],
       [True, True, False, False, True, True, False, False, False, False, True, True, False, True, True, False, False],
       [True, True, False, True, True, False, False, True, True, True, True, True, True, True, True, True, False],
       [True, True, False, True, True, False, False, False, False, False, True, True, False, False, False, False, False],
       [True, True, False, True, False, False, False, False, False, False, True, True, False, False, False, False, False],
       [True, True, False, True, False, False, False, False, False, False, True, True, False, False, True, True, False],
       [True, True, False, True, True, False, False, True, True, True, True, True, True, True, True, True, True],
       [True, True, False, False, True, True, False, False, False, False, False, True, False, False, False, False, False],
       [True, True, False, False, True, True, False, True, True, True, False, True, False, False, True, True, True],
       [True, True, False, False, True, True, False, True, True, False, False, True, False, False, True, True, False],
       [True, True, False, False, True, True, False, True, True, False, True, True, False, False, True, True, False],
       [True, True, True, True, True, True, False, True, True, False, True, True, False, False, True, True, False],
       [True, True, False, False, False, False, False, True, True, False, True, True, False, False, True, True, False],
       [True, True, False, False, False, False, False, True, True, False, True, True, False, False, True, True, False],
       [True, True, False, False, False, False, False, True, True, True, True, True, True, True, True, True, False],
       [True, True, False, False, False, False, False, True, True, False, False, False, False, False, True, True, False]],

'七': [[False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, True, True, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, True, True, True, True],
       [False, False, False, True, True, True, True, True, True, True, True, True, True, True, False, False, False],
       [True, True, True, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, False, False]],

'柒': [[False, False, True, True, False, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, True, True, True, False, False, True, True, False, False, False, False, False, False],
       [True, True, False, False, False, False, False, False, True, True, False, False, False, True, True, True],
       [False, True, True, True, False, True, True, True, True, True, True, True, True, True, False, False],
       [False, False, True, True, False, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, True, True, True, True, False, True, True, True],
       [False, False, True, True, False, False, False, False, False, False, False, True, True, True, False, False],
       [False, True, True, False, False, False, False, True, True, True, False, False, False, False, False, False],
       [True, True, False, False, False, False, False, True, True, False, False, False, False, True, True, False],
       [True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, True, True, False, False, True, True, False, False, False],
       [False, False, False, True, True, False, False, True, True, False, False, False, True, True, True, False],
       [False, False, True, True, True, False, False, True, True, False, False, False, False, True, True, True],
       [False, True, True, False, False, False, False, True, True, False, False, False, False, False, True, True],
       [False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False]],

'八': [[False, False, False, False, False, False, False, False, True, True, True, True, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, True, True, True, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, True, True, False, False, False, False, False, False, False, True, True, True, False, False, False],
       [False, True, True, False, False, False, False, False, False, False, False, False, True, True, True, False, False],
       [False, True, True, False, False, False, False, False, False, False, False, False, False, True, True, True, False],
       [True, True, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True]],

'捌': [[False, True, True, True, False, False, False, False, True, True, False, False, False, False, True, True, True],
       [False, True, True, False, False, True, True, True, True, True, False, False, False, False, True, True, False],
       [False, True, True, False, False, True, True, False, True, True, False, True, True, True, True, True, False],
       [False, True, True, False, False, False, True, False, True, True, False, True, True, False, True, True, False],
       [True, True, True, True, True, False, True, False, True, True, False, True, True, False, True, True, False],
       [False, True, True, False, False, False, True, True, True, True, False, True, True, False, True, True, False],
       [False, True, True, False, False, False, True, True, False, False, False, True, True, False, True, True, False],
       [False, True, True, False, False, False, True, True, False, False, False, False, True, False, True, True, False],
       [False, True, True, False, True, False, True, True, True, True, True, False, True, False, True, True, False],
       [False, True, True, True, False, False, True, True, True, True, False, False, True, False, True, True, False],
       [True, True, True, False, False, True, True, False, True, True, False, True, True, False, True, True, False],
       [False, True, True, False, False, True, True, False, True, True, False, True, True, False, True, True, False],
       [False, True, True, False, False, True, True, False, True, True, False, True, True, False, True, True, False],
       [False, True, True, False, False, True, True, False, True, True, False, False, False, False, True, True, False],
       [False, True, True, False, True, True, False, False, True, True, False, False, False, False, True, True, False],
       [False, True, True, False, True, True, False, True, True, True, False, True, True, True, True, True, False],
       [True, True, True, False, False, False, False, True, True, False, False, False, False, False, False, False, False]],

'九': [[False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, False, True, True, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, False, True, True, False, False, False, False, False, True, True, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, True, True, False, False, True, True, False],
       [False, False, True, True, False, False, False, False, False, False, False, True, True, True, False, True, True, True],
       [True, True, True, False, False, False, False, False, False, False, False, False, True, True, True, True, True, False]],

'玖': [[False, False, False, False, False, False, False, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, False, True, True, True, False, True, True, False, False, False, False, False, False, False],
       [True, True, True, True, True, True, True, True, False, True, True, False, False, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, True, True, True, True, True, True, True, False, False],
       [False, False, False, True, True, False, False, False, False, True, True, False, False, True, True, False, False, False],
       [False, False, False, True, True, False, False, False, True, True, False, False, False, True, True, False, False, False],
       [False, False, False, True, True, False, True, False, True, True, False, False, False, True, True, False, False, False],
       [False, True, True, True, True, True, True, True, True, False, False, False, False, True, True, False, False, False],
       [False, False, False, True, True, False, False, True, True, False, False, False, True, True, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, False, True, True, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, True, True, True, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, True, True, True, True, False, False, False, False],
       [False, False, False, True, True, False, True, True, False, False, True, True, False, True, True, False, False, False],
       [True, True, True, True, True, True, False, False, False, True, True, False, False, True, True, False, False, False],
       [False, True, True, False, False, False, False, False, True, True, False, False, False, False, True, True, False, False],
       [False, False, False, False, False, False, True, True, True, False, False, False, False, False, False, True, True, True]],

'零': [[False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False],
       [False, False, False, False, False, False, False, True, True, False, False, False, False, False, False, False, False, False],
       [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True],
       [True, True, False, True, True, True, True, True, True, False, False, True, True, True, False, True, True, False],
       [True, True, False, False, False, False, False, True, True, False, True, True, False, False, True, True, False, False],
       [False, True, True, True, True, True, True, True, True, False, True, True, True, True, False, False, False, False],
       [False, True, True, False, False, False, False, True, True, False, False, False, False, False, True, True, False, False],
       [False, False, False, False, False, False, True, True, False, True, True, False, False, False, False, False, False, False],
       [False, False, False, False, True, True, True, True, True, True, True, True, False, False, False, False, False, False],
       [False, False, True, True, True, False, False, False, False, False, False, True, True, True, True, True, True, False],
       [True, True, True, False, True, True, True, True, True, True, True, True, True, True, False, True, True, False],
       [False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, False, False],
       [False, False, False, False, False, True, True, False, False, False, True, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, True, True, True, True, True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, True, True, True, False, False, False, False, False, False]],

'+': [[False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False],
      [True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False]],

'加': [[False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, False, False, False, False, False],
       [False, False, False, True, True, False, False, False, False, False, False, False, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, False, True, True, True, True, True],
       [True, True, True, True, True, True, True, True, True, True, False, True, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, False, True, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, False, True, True, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, True, True, False, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, True, True, False, False, False, True, True, False, True, True, False, False, True, True],
       [False, False, True, True, False, False, True, True, False, False, True, True, False, False, True, True],
       [False, True, True, False, False, False, True, True, False, False, True, True, False, False, True, True],
       [False, True, True, False, False, False, True, True, False, False, True, True, True, True, True, True],
       [True, True, False, False, True, True, True, False, False, False, True, True, False, False, False, False]],

'=': [[True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True],
      [False, False, False, False, False, False, False, False, False],
      [False, False, False, False, False, False, False, False, False],
      [True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True],
      [True, True, True, True, True, True, True, True, True]],

'?': [[False, False, True, True, True, True, True, False, False],
      [False, True, True, True, True, True, True, True, False],
      [True, True, True, True, False, False, True, True, True],
      [True, True, True, False, False, False, True, True, True],
      [False, False, False, False, False, True, True, True, True],
      [False, False, False, False, True, True, True, True, False],
      [False, False, False, True, True, True, True, False, False],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, False, False, False, False, False, False],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False],
      [False, False, False, True, True, True, False, False, False]],
}
